language: cpp
install:
  - pushd $(mktemp -d)
  - curl -O https://capnproto.org/capnproto-c++-0.6.1.tar.gz
  - tar zxf capnproto-c++-0.6.1.tar.gz
  - cd capnproto-c++-0.6.1
  - ./configure
  - make -j6 check
  - sudo make install
  - popd
before_script: mkdir build && cd build
script:
  - cmake ../.
  - cmake --build . -- -j
  - ctest --output-on-failure
