language: cpp
install:
  - pushd $(mktemp -d)
  # Cap'n Proto
  - curl -O https://capnproto.org/capnproto-c++-0.6.1.tar.gz
  - tar zxf capnproto-c++-0.6.1.tar.gz
  - cd capnproto-c++-0.6.1
  - ./configure
  - make -j
  - sudo make install
  # libsodium
  - curl -O https://download.libsodium.org/libsodium/releases/libsodium-1.0.16.tar.gz
  - tar zxf libsodium-1.0.16.tar.gz
  - cd libsodium-1.0.16
  - ./configure
  - make -j
  - sudo make install
  - popd
addons:
  apt:
    packages:
      - doxygen
before_script: mkdir build && cd build
script:
  - cmake ../.
  - cmake --build . -- -j
  - ctest --output-on-failure
